### ISSUE TITLE
looks good to me, just tried it

### ISSUE THREAD

**Issue by alexmyczko** [ftoledo/pkg-multiblend#1]
will it make it into buster?

**Comment by ftoledo** [comment]
Yes, it's build on Debian Buster.

I was upload to mentors too:
https://mentors.debian.net/package/multiblend

And search for sponsor: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911779
Can you sponsor the package?

Build log attached:
[multiblend_0.6.2-1_amd64.build.txt](https://github.com/ftoledo/pkg-multiblend/files/2796958/multiblend_0.6.2-1_amd64.build.txt)

Thanks!

**Comment by alexmyczko** [comment]
Unfortunately I'm not DD, so I can't sponsor. I forwarded it to my usual sponsor... I hope it'll make it into buster.

**Comment by ftoledo** [comment]
Ok! I'll be very greatful!
